websocketpp: Keep patch override and document its requirement for ROBORIO
The websocketpp patch is required for the ROBORIO build
(arm-frc-linux-gnueabi-gcc).  It fails to compile
cpp/foxglove-websocket/src/server_factory.cpp because of
syntax errors in basic.hpp:

error: expected ')' before 'h'
  basic<concurrency,names>(channel_type_hint::value h =

Because this is a workaround for a weird, old compiler, don't worry
about it.  Nothing downstream will need the patch.

Change-Id: I606dc00133c047b381b71b33ec742f19bd4aa158
Signed-off-by: Austin Schuh <austin.linux@gmail.com>