aos: Add missing mutex unlock in `lockless_queue_test.cc`
Upgrading to a newer clang gives us this error:

    external/aos/aos/ipc_lib/lockless_queue_test.cc:354:1: error: mutex 'sender_running' is not held on every path through here [-Werror,-Wthread-safety-analysis]
      354 | }
          | ^
    external/aos/aos/ipc_lib/lockless_queue_test.cc:291:26: note: mutex acquired here
      291 |   while (!sender_running.try_lock()) {
          |                          ^

Fix the error by automatically unlocking the mutex after we're done
using it. The `unique_lock` class seems useful here.

Signed-off-by: James Kuszmaul <james.kuszmaul@bluerivertech.com>
Change-Id: Ie557f038b5154b3b4b96b1bd03d051a95cac07cf